config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount Bootsy::Engine => "/bootsy", as: "bootsy"

  root "static_pages#index"

  resources :books, only: [:index, :show, :update] do
    resource :book_user, only: [:create, :update]
  end
  resources :reviews, except: [:index, :show]
  resources :comments, except: [:index, :show]
  resources :requests, except: [:edit, :update]

  namespace :admin do
    root "categories#index"
    resources :books
    resources :categories
    resources :requests, only: [:index, :update]
    resources :users, only: [:index,:destroy]
  end

  resources :users do
    get "/:relationship" => "relationships#index", as: :relationship,
      constraints: {relationship: /(following|followers)/}
  end

  resources :relationships, only: [:index, :create, :destroy]
  resources :likes, only:[:create, :destroy]
end

app/models/book.rb
class Book < ActiveRecord::Base
  include Bootsy::Container

  belongs_to :category

  has_many :users, through: :book_users
  has_many :book_users, dependent: :destroy
  has_many :reviews, dependent: :destroy

  extend FriendlyId
  friendly_id :title, use: :slugged

  mount_uploader :cover, CoverUploader

  validates :title, presence: true
  validates :author, presence: true
  validates :num_pages, presence: true, numericality: {minimum: 1}
  validates :publish_date, presence: true
  validates :category, presence: true
  validate :check_day_present, on: [:create, :update]

  def cover_default
    cover.present? ? cover : Settings.book.cover_default
  end

  private
  UNRANSACKABLE_ATTRIBUTES = ["id", "updated_at", "category_id", "created_at", "slug", "description"]

  def self.ransackable_attributes auth_object = nil
    column_names - UNRANSACKABLE_ATTRIBUTES + _ransackers.keys
  end

  def check_day_present
    errors.add :publish_date,
      I18n.t("error.wrong_date") if self.publish_date.present? && self.publish_date.to_date > Date.today
  end
end

app/controllers/admin/books_controller.rb
class Admin::BooksController < ApplicationController
  before_action :find_book, except: [:new, :create, :index]
  before_action :authenticate_user!
  before_action :verify_admin

  def index
    @books = Book.order("title").paginate page: params[:page],
      per_page: Settings.paginate_per_page
  end

  def new
    @categories = Category.all
    @book = Book.new
  end

  def create
    @book = Book.new book_params
    if @book.save
      flash[:success] = t "flash.book.created.success"
      redirect_to admin_books_path
    else
      flash[:danger] = t "flash.book.created.fails"
      @categories = Category.all
      render :new
    end
  end

  def edit
    @categories = Category.all
  end

  def update
    if @book.update book_params
      flash[:success] = t "flash.book.updated.success"
      redirect_to admin_books_path
    else
      flash[:danger] = t "flash.book.updated.fails"
      @categories = Category.all
      render :edit
    end
  end

  private
  def book_params
    params.require(:book).permit(:title, :author, :num_pages, :publish_date,
      :description, :rate, :category_id, :cover, :bootsy_image_gallery_id)
  end

  def find_book
    @book = Book.friendly.find params[:id]
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, only: [:index, :show]
  before_action :load_book, only: :show

  def index
    @search = Book.search params[:q]
    @search.build_condition if @search.conditions.empty?
    @search.build_sort if @search.sorts.empty?
    @books = @search.result.paginate page: params[:page], per_page: Settings.paginate_per_page
  end

  def show
    if current_user
      @book_user = BookUser.find_or_initialize_by user_id: current_user,
        book_id: @book.id
    end
    @reviews = @book.reviews.latest
    @comment = current_user.comments.build
  end

  private
  def load_book
    @book = Book.friendly.find params[:id]
  end
end

app/views/admin/books/_book.html.erb
<div class="col-md-3 col-sm-4 col-xs-6">
  <div class="book-item">
    <div class="flip">
      <div class="front text-center">
        <%= image_tag book.cover.thumb.url, class: "img-responsive book-img",
          alt: book.title %>
      </div>
      <div class="back">
        <p class="short-desc">
          <%= book.description %>
        </p>
        <%= link_to t("book.button.show"), edit_admin_book_path(book),
          class: "btn btn-sm btn-primary btn-view" %>
      </div>
    </div>
    <h3 class="title">
      <%= link_to book.title, edit_admin_book_path(book) %>
    </h3>
    <p class="author">
      <%= book.author %>
    </p>
  </div>
</div>

app/views/admin/books/_form.html.erb
<%= form_for [:admin, @book], html: {multipart: true} do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <div class="form-group">
    <%= f.label :category_id %>
    <%= f.select :category_id, options_for_select(@categories.map{|c| [c.name, c.id ]},
      selected_key = f.object.category_id), {}, class: "form-control" %>
  </div>
  <div class="form-group">
    <div class="input-group">
      <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
      <%= f.text_field :title, class: "form-control",
        placeholder: t("book.title") %>
    </div>
  </div>
  <div class="form-group image-container">
    <div class="input-group">
      <%= f.file_field :cover %>
      <div class="preview pull-right">
        <%= image_tag @book.cover.thumb.url, class: "img-responsive",
          id: "preview_cover" %>
      </div>
    </div>
  </div>
  <div class="form-group">
    <div class="input-group">
      <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
      <%= f.text_field :author, class: "form-control",
        placeholder: t("book.author") %>
    </div>
  </div>
  <div class="form-group">
    <%= f.bootsy_area :description, rows: 15, class: "form-control",
      placeholder: t("book.description") %>
  </div>
  <div class="form-group">
    <div class="input-group">
      <%= f.text_field :publish_date, class: "form-control datepicker",
        placeholder: t("book.publish_date") %>
      <span class="input-group-addon"><i class="glyphicon glyphicon-time"></i></span>
    </div>
  </div>
  <div class="form-group">
    <div class="input-group">
      <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
      <%= f.number_field :num_pages, class: "form-control",
        max: Settings.book.num_page_max, min: Settings.book.num_page_min,
        placeholder: t("book.num_pages") %>
    </div>
  </div>
  <div class="actions">
    <%= f.submit t("book.button.submit"), class: "btn btn-primary pull-right" %>
  </div>
<% end %>

app/views/admin/books/edit.html.erb
<% provide :title, t("book.edit", title: @book.title) %>

<div class="row">
  <hr>
  <div class="col-md-8 col-md-offset-2">
    <h1 class="text-info text-center">
      <%= t "book.edit", title: @book.title %>
    </h1>
    <br>
    <%= render "form" %>
  </div>
</div>

app/views/admin/books/index.html.erb
<% provide :title, t("book.all_book") %>

<div class="row">
  <hr>
  <h1 class="text-info text-center">
    <%= t "book.all_book" %>
  </h1>
  <div class="block book-container">
    <%= render @books %>
  </div>
</div>
<%= will_paginate %>

app/views/admin/books/new.html.erb
<% provide :title, t("book.new") %>
<h1><%= t "book.new" %></h1>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <div class="row">
      <%= form_for [:admin, @book] do |f| %>
        <%= render "shared/error_messages", object: f.object %>
        <div class="form-group">
          <%= f.label :category_id %>
          <%= f.select :category_id, options_for_select(@categories.map{|c| [c.name, c.id ]},
            selected_key = f.object.category_id), {}, class: "form-control" %>
        </div>
        <div class="form-group">
          <div class="input-group">
            <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
            <%= f.text_field :title, class: "form-control",
              placeholder: t("book.title") %>
          </div>
        </div>
        <div class="form-group">
          <div class="input-group">
            <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
            <%= f.text_field :author, class: "form-control",
              placeholder: t("book.author") %>
          </div>
        </div>
        <div class="form-group">
          <%= f.bootsy_area :description, rows: 15, class: "form-control",
            placeholder: t("book.description") %>
        </div>
        <div class="form-group">
          <div class="input-group">
            <%= f.text_field :publish_date, class: "form-control datepicker",
              placeholder: t("book.publish_date") %>
            <span class="input-group-addon"><i class="glyphicon glyphicon-time"></i></span>
          </div>
        </div>
        <div class="form-group">
          <div class="input-group">
            <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
            <%= f.number_field :num_pages, class: "form-control",
              max: Settings.book.num_page_max, min: Settings.book.num_page_min,
              placeholder: t("book.num_pages") %>
          </div>
        </div>
        <div class="actions">
          <%= f.submit t("book.button.create"), class: "btn btn-primary pull-right" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class="clear"></div>