config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount Bootsy::Engine => "/bootsy", as: "bootsy"

  root "static_pages#index"

  resources :books, only: [:index, :show, :update] do
    resource :book_user, only: [:create, :update]
  end
  resources :reviews, except: [:index, :show]
  resources :comments, except: [:index, :show]
  resources :requests, except: [:edit, :update]

  namespace :admin do
    root "categories#index"
    resources :books
    resources :categories
    resources :requests, only: [:index, :update]
    resources :users, only: [:index,:destroy]
  end

  resources :users do
    get "/:relationship" => "relationships#index", as: :relationship,
      constraints: {relationship: /(following|followers)/}
  end

  resources :relationships, only: [:index, :create, :destroy]
  resources :likes, only:[:create, :destroy]
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t "error.form" %> <%= pluralize(object.errors.count, t("error.error")) %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li>
          <%= msg %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= user_relationship_path @user, relationship: :following %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    <%= t "user.following" %>
  </a>
  <a href="<%= user_relationship_path @user, relationship: :followers %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    <%= t "user.followers" %>
  </a>
</div>