config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount Bootsy::Engine => "/bootsy", as: "bootsy"

  root "static_pages#index"

  resources :books, only: [:index, :show, :update] do
    resource :book_user, only: [:create, :update]
  end
  resources :reviews, except: [:index, :show]
  resources :comments, except: [:index, :show]
  resources :requests, except: [:edit, :update]

  namespace :admin do
    root "categories#index"
    resources :books
    resources :categories
    resources :requests, only: [:index, :update]
    resources :users, only: [:index,:destroy]
  end

  resources :users do
    get "/:relationship" => "relationships#index", as: :relationship,
      constraints: {relationship: /(following|followers)/}
  end

  resources :relationships, only: [:index, :create, :destroy]
  resources :likes, only:[:create, :destroy]
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :books, dependent: :destroy

  validates :name, presence: true
  validates :description, presence: true, length: {minimum: 10}

  extend FriendlyId
  friendly_id :name, use: :slugged

  scope :latest, -> {order created_at: :desc}

  private
  UNRANSACKABLE_ATTRIBUTES = ["id", "updated_at", "created_at", "slug"]

  def self.ransackable_attributes auth_object = nil
    column_names - UNRANSACKABLE_ATTRIBUTES + _ransackers.keys
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :load_category, except: [:index, :new, :create]
  before_action :verify_admin

  def index
    @categories = Category.latest.paginate page: params[:page],
      per_page: Settings.category.per_page
  end

  def show
    @books = @category.books
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new category_params
    if @category.save
      flash[:success] = t "flash.category.created.success"
      redirect_to [:admin, @category]
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @category.update category_params
      flash[:success] = t "flash.category.updated.success"
      redirect_to [:admin, @category]
    else
      render "edit"
    end
  end

  def destroy
    if @category.destroy
      flash[:success] = t("flash.category.deleted.success")
    else
      flash[:failed] = t("flash.category.deleted.failed")
    end
    redirect_to admin_root_path
  end

  private
  def load_category
    @category = Category.friendly.find params[:id]
  end

  def category_params
    params.require(:category).permit :name, :description
  end
end

app/views/admin/categories/_category.html.erb
<tr>
  <td>
    <%= category.name %>
  </td>
  <td>
    <%= category.description.truncate 100 %>
  </td>
  <td><%= category.books.count %></td>
  <td>
    <%= link_to t("category.button.edit"),
      edit_admin_category_path(category), class: "btn btn-primary" %>
  </td>
  <td>
    <%= link_to t("category.buttons.delete"),
      admin_category_path(category), method: :delete, class: "btn btn-danger",
      data: {confirm: t("category.messages.confirm")} %>
  </td>
</tr>

app/views/admin/categories/_form.html.erb
<%= form_for [:admin, @category] do |f| %>
  <%= render "shared/error_messages", object: @category %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control", rows: 10 %>
  </div>
  <ul class="list-inline">
    <li>
      <%= f.submit t("category.button.create"), class: "btn btn-success" %>
    </li>
    <li>
      <%= button_tag t("category.button.reset"), type: :reset,
        class: "btn btn-default" %>
    </li>
  </ul>
<% end %>

app/views/admin/categories/edit.html.erb
<% provide :title, t("category.title") %>
<div class="page-header">
  <%= link_to t("category.buttons.cancel"), admin_category_path(@category),
    class: "btn btn-default pull-right" %>
  <h3><%= t "category.edit_category" %></h3>
</div>
<div class="row">
  <div class="col-xs-8 col-xs-offset-2">
    <%= render "form" %>
  </div>
</div>

app/views/admin/categories/index.html.erb
<% provide :title, t("category.title") %>
<div class="page-header">
  <%= link_to t("category.buttons.new"), new_admin_category_path,
    class: "btn btn-default pull-right" %>
  <h3><%= t "category.title" %></h3>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= t "category.title" %></th>
      <th><%= t "category.description" %></th>
      <th><%= t "category.books_count" %></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <%= render @categories %>
    <%= will_paginate @categories%>
  </tbody>
</table>

app/views/admin/categories/new.html.erb
<% provide :title, t("category.title") %>
<div class="page-header">
  <%= link_to t("category.buttons.cancel"), admin_root_path,
    class: "btn btn-default pull-right" %>
  <h3><%= t("category.create_category") %></h3>
</div>
<div class="row">
  <div class="col-xs-8 col-xs-offset-2">
    <%= render "form" %>
  </div>
</div>

app/views/admin/categories/show.html.erb
<% provide :title, @category.name %>
<div class="page-header">
  <ul class="list-inline pull-right">
    <li>
      <%= link_to t("application.buttons.edit"),
        edit_admin_category_path(@category), class: "btn btn-primary" %>
    </li>
    <li>
      <%= link_to t("application.buttons.delete"), [:admin, @category],
        method: :delete, data: {confirm: t("category.messages.confirm")},
        class: "btn btn-danger" %>
    </li>
  </ul>
  <h3><%= @category.name %></h3>
</div>
<div class="row">
  <div class="col-lg-12">
    <p><%= @category.description %></p><br />
    <fieldset class="fsStyle">
      <legend class="legendStyle">
        <span class="label label-info"><%= t "book.books" %></span>
      </legend>
      <% @books.each do |book| %>
        <div class="col-lg-2">
          <div class="thumbnail text-center">
            <h5><%= book.title %></h5>
          </div>
        </div>
      <% end %>
    </fieldset>
  </div>
</div>