config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount Bootsy::Engine => "/bootsy", as: "bootsy"

  root "static_pages#index"

  resources :books, only: [:index, :show, :update] do
    resource :book_user, only: [:create, :update]
  end
  resources :reviews, except: [:index, :show]
  resources :comments, except: [:index, :show]
  resources :requests, except: [:edit, :update]

  namespace :admin do
    root "categories#index"
    resources :books
    resources :categories
    resources :requests, only: [:index, :update]
    resources :users, only: [:index,:destroy]
  end

  resources :users do
    get "/:relationship" => "relationships#index", as: :relationship,
      constraints: {relationship: /(following|followers)/}
  end

  resources :relationships, only: [:index, :create, :destroy]
  resources :likes, only:[:create, :destroy]
end

app/models/activity.rb
class Activity < ActiveRecord::Base
  belongs_to :user

  has_many :likes, dependent: :destroy

  validates :user, presence: true
  validates :target_id, presence: true
  validates :content, presence: true

  scope :latest, ->{order updated_at: :desc}

  def create_activity target_id, content
    case content
    when Settings.activities.followed, Settings.activities.unfollowed
      "#{Settings.activities.user} #{User.find_by(id: target_id).name}"
    when Settings.activities.reviewed
      "#{Settings.activities.book} #{Book.find_by(id: target_id).title}"
    when Settings.activities.commented
      "#{Settings.activities.user} #{Review.find_by(id: target_id).content.truncate 100}"
    end
  end
end

app/views/activities/_activity.html.erb
<tr id="activity-<%= activity.id %>">
  <td>
    <div class="row">
      <div class="col-xs-12">
        <%= link_to activity.user.name, activity.user %>
        <strong><%= activity.content %></strong>
        <%= activity.create_activity activity.target_id, activity.content %>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12">
        <%= link_to likes_path(action_type: like_type(current_user, activity)), method: :post, data: {params: "activity_id=#{activity.id}"}, remote: true do %>
        <i class="glyphicon glyphicon-thumbs-up"></i>
        <span><%= like_status(current_user, activity) ? t("activity.unlike") : t("activity.like") %></span>
        <% end %>
      </div>
    </div>
  </td>
</tr>